DateTable = 
ADDCOLUMNS (
    CALENDAR (DATE(2000, 1, 1), DATE(2025, 12, 31)),
    "YearMonth", FORMAT([Date], "YYYY-MM")
)

MoMChange_SelectedDate = 
VAR SelectedDate = MAX('DateTable'[Date])
VAR SelectedYearMonth = FORMAT(SelectedDate, "YYYY-MM")
VAR PreviousMonth = FORMAT(DATEADD(SelectedDate, -1, MONTH), "YYYY-MM")
RETURN
IF(
    ISBLANK(PreviousMonth), 
    BLANK(), 
    CALCULATE(
        [DistinctIDCount], 
        'YourTable'[YearMonth] = SelectedYearMonth
    ) - 
    CALCULATE(
        [DistinctIDCount], 
        'YourTable'[YearMonth] = PreviousMonth
    )
)
