MoM Change = 
VAR CurrentMonthCount = CALCULATE(DISTINCTCOUNT('Table'[ID]), ALLSELECTED('Table'[Date]))
VAR PreviousMonth = EDATE( MAX( ALLSELECTED('Table'[Date]) ), -1)
VAR PreviousMonthCount = 
    CALCULATE(DISTINCTCOUNT('Table'[ID]), 
              ALL('Table'[Date]), 
              'Table'[Date] <= PreviousMonth, 
              'Table'[Date] > EOMONTH(PreviousMonth, -1))
VAR Change = CurrentMonthCount - PreviousMonthCount
RETURN 
    IF(ISBLANK(Change), 
       BLANK(), 
       IF(Change > 0, 
          CONCATENATE("↑", FORMAT(Change, "General Number")), 
          IF(Change < 0, 
             CONCATENATE("↓", FORMAT(-Change, "General Number")), 
             "0"
          )
       )
    )
