MoM Change = 
VAR SelectedDate = MAX('Table'[Date])
VAR CurrentMonthStart = EOMONTH(SelectedDate, -1) + 1
VAR CurrentMonthEnd = EOMONTH(SelectedDate, 0)
VAR PreviousMonthStart = EOMONTH(SelectedDate, -2) + 1
VAR PreviousMonthEnd = EOMONTH(SelectedDate, -1)
VAR CurrentMonthCount = CALCULATE(DISTINCTCOUNT('Table'[ID]), 'Table'[Date] >= CurrentMonthStart, 'Table'[Date] <= CurrentMonthEnd)
VAR PreviousMonthCount = CALCULATE(DISTINCTCOUNT('Table'[ID]), 'Table'[Date] >= PreviousMonthStart, 'Table'[Date] <= PreviousMonthEnd)
VAR Change = CurrentMonthCount - IF(ISBLANK(PreviousMonthCount), 0, PreviousMonthCount)
RETURN 
    IF(Change = 0, 
       "0", 
       IF(Change > 0, 
          CONCATENATE("↑", FORMAT(Change, "General Number")), 
          CONCATENATE("↓", FORMAT(-Change, "General Number"))
       )
    )
